urlShortener/short_url/short_url/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('shorturlapp/', include('shorturlapp.urls')),
    path('admin/', admin.site.urls),
]

urlShortener/short_url/shorturlapp/urls.py
from django.urls import path

from . import views
app_name = 'shorturlapp'
urlpatterns = [
    path('', views.submit_url, name='index'),
    path('submit_url', views.submit_url, name='submit_url'),
    path('<random_code>', views.short_url, name='short_url'),
]

urlShortener/short_url/shorturlapp/models.py
from django.db import models


class NewUrl(models.Model):
    code = models.CharField(max_length=6)
    url = models.TextField()
    clicks = models.IntegerField(default=0)

    def __str__(self):
        return self.code

urlShortener/short_url/shorturlapp/forms.py
from django import forms


class ShortUrlForm(forms.Form):
    submit_url = forms.CharField(label='Big Url', max_length=200)

urlShortener/short_url/shorturlapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import NewUrl
from .forms import ShortUrlForm

import random
import string


def submit_url(request):
    lettersNDigits = string.ascii_letters + string.digits
    random_code = ''.join(random.choice(lettersNDigits) for i in range(6))
    myUrl = NewUrl.objects.order_by('-id')[0]
    if request.method == 'POST':
        form = ShortUrlForm(request.POST)
        if form.is_valid():
            submit_url = form.cleaned_data['submit_url']
            myUrl = NewUrl(url=submit_url, code=random_code)
            myUrl.save()
            form = ShortUrlForm()
            return HttpResponseRedirect(reverse('shorturlapp:index'))
    else:
        form = ShortUrlForm()
    context = {'form': form, 'myUrl': myUrl}
    return render(request, 'shorturlapp/index.html', context)


def short_url(request, random_code):
    # GET request to go to site with short_url code
    this_url = NewUrl.objects.get(code=random_code)
    this_url.clicks += 1
    this_url.save()
    return HttpResponseRedirect(this_url.url)
    # will add one to the "count" in database

urlShortener/short_url/shorturlapp/templates/shorturlapp/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Short Urls by Cruzertech</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'shorturlapp/styles.css' %}"/>
  </head>
  <body>
    <h1><strong>Please input a url to shorten:</strong></h1>
  	<div class="container">
      <div class="five columns">
        <div class="offset-by-nine columns">
          <form action="{% url 'shorturlapp:submit_url' %}" method="post">
        		{% csrf_token %}
        		{{ form }}
        		<input type="submit" value="Shorten">
            <p>Your shortened URL is: {{ myUrl.code }}. <br> Copy/paste it to the end of the url above ^ </p>
        	</form>
        </div>
      </div>
    </div>
  </body>
</html>