groceryList/grocery_list/grocery_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('grocerylist/', include('grocerylist.urls')),
    path('admin/', admin.site.urls),
]

groceryList/grocery_list/grocerylist/urls.py
from django.urls import path

from . import views
app_name = 'grocerylist'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_item, name='add_item'),
    path('delete/<int:pk>', views.delete_item, name='delete_item')
]

groceryList/grocery_list/grocerylist/models.py
import datetime

from django.db import models
from django.utils import timezone


class GroceryItem(models.Model):
    text_description = models.CharField(max_length=200)
    created_date = models.DateTimeField('date published')
    completed_date = models.DateTimeField('date completed', null=True, blank=True)
    completed_yn = models.BooleanField(default=False)

    def __str__(self):
        return self.text_description

    def was_published_recently(self):
        return self.created_date >= timezone.now() - datetime.timedelta(days=1)

groceryList/grocery_list/grocerylist/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from .models import GroceryItem


def index(request):
    latest_grocery_list = GroceryItem.objects.order_by('created_date')
    context = {'latest_grocery_list': latest_grocery_list}
    return render(request, 'grocerylist/index.html', context)


def add_item(request):
    if request.method == 'POST':
        add_item = request.POST['add_item']
        created_date = timezone.now()
        new_item = GroceryItem(text_description=add_item, created_date=created_date)
        new_item.save()
        return HttpResponseRedirect(reverse('grocerylist:index'))


def delete_item(request, pk):
    delete_item = get_object_or_404(GroceryItem, pk=pk)
    delete_item.delete()
    return HttpResponseRedirect(reverse('grocerylist:index'))

groceryList/grocery_list/grocerylist/templates/grocerylist/index.html
{% if latest_grocery_list %}
	<form action='{% url "grocerylist:add_item" %}' method="post">
		{% csrf_token %}
		<input type="text" name="add_item">
		<input type="submit" value="Add">
	</form>
    <ul>
    {% for item in latest_grocery_list %}
    	<form action="{% url 'grocerylist:delete_item' item.id %}" method="post">
    		{% csrf_token %}
	        <li>
	        	{{ item.text_description }}
	        	<input type="submit" value="Delete">
	        </li>
    	</form>
    {% endfor %}
    </ul>
{% else %}
    <p>Your list is empty.</p>
{% endif %}

groceryList/grocery_list/grocerylist/templates/grocerylist/item.html
<form action="/add/" method="post">
	{% csrf_token %}
	<input type="text" name="add_item">
	<input type="submit" name="Add">
</form>